"use client";

import CreatePost from "../Utils/CreatePost";
import PostCard from "../Utils/PostCard";

export default function ForYou({ className }: any) {
  return (
    <div className={`space-y-4 ${className}`}>
      <CreatePost
        avatarImgSrc="https://avatars.githubusercontent.com/u/168587972?s=96&v=4"
      />

      <PostCard
        avatarImgSrc="https://avatars.githubusercontent.com/u/168587972?s=96&v=4"
        name="Generated By Humans"
        username="@GBH"
        postContext="Follow for more!"
      />
    </div >
  );
}
