"use client";

import { useState } from "react";
import CreatePost from "../Utils/CreatePost";
import PostCard from "../Utils/PostCard";

export default function ForYou({ className }: any) {
  const [posts, setPosts] = useState([
    {
      avatarImgSrc: "https://avatars.githubusercontent.com/u/168587972?s=96&v=4",
      name: "Generated By Humans",
      username: "@GBH",
      postContent: "Follow for more!",
    },
    {
      avatarImgSrc: "https://avatars.githubusercontent.com/u/168587972?s=96&v=4",
      name: "Generated By Humans",
      username: "@GBH",
      postContent: "Follow for more!",
    },
    {
      avatarImgSrc: "https://avatars.githubusercontent.com/u/168587972?s=96&v=4",
      name: "Generated By Humans",
      username: "@GBH",
      postContent: "Follow for more!",
    },
    {
      avatarImgSrc: "https://avatars.githubusercontent.com/u/168587972?s=96&v=4",
      name: "Generated By Humans",
      username: "@GBH",
      postContent: "Follow for more!",
    },
  ]);

  const addPost = (newPost) => {
    setPosts([newPost, ...posts]); // Add the new post to the beginning of the list
  };

  return (
    <div className={`space-y-4 ${className}`}>
      <CreatePost
        avatarImgSrc="https://lh3.googleusercontent.com/a/ACg8ocJxGhbK6kWhiM1UIjYcf5xv_u9_hr8AW4354HuPJbo_7jjdWKo=s288-c-no"
        addPost={addPost}
      />
      {posts.map((post, index) => (
        <PostCard
          key={index}
          avatarImgSrc={post.avatarImgSrc}
          name={post.name}
          username={post.username}
          postContent={post.postContent}
        />
      ))}
    </div>
  );
}
